// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package controllerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// NodeManagementClient is the client API for NodeManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeManagementClient interface {
	RegisterNode(ctx context.Context, in *NodeRegisterRequest, opts ...grpc.CallOption) (*NodeRegisterReply, error)
	UnregisterNode(ctx context.Context, in *NodeRegisterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Heartbeat(ctx context.Context, in *NodeHeartbeat, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type nodeManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeManagementClient(cc grpc.ClientConnInterface) NodeManagementClient {
	return &nodeManagementClient{cc}
}

func (c *nodeManagementClient) RegisterNode(ctx context.Context, in *NodeRegisterRequest, opts ...grpc.CallOption) (*NodeRegisterReply, error) {
	out := new(NodeRegisterReply)
	err := c.cc.Invoke(ctx, "/controller.NodeManagement/RegisterNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeManagementClient) UnregisterNode(ctx context.Context, in *NodeRegisterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/controller.NodeManagement/UnregisterNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeManagementClient) Heartbeat(ctx context.Context, in *NodeHeartbeat, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/controller.NodeManagement/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeManagementServer is the server API for NodeManagement service.
// All implementations should embed UnimplementedNodeManagementServer
// for forward compatibility
type NodeManagementServer interface {
	RegisterNode(context.Context, *NodeRegisterRequest) (*NodeRegisterReply, error)
	UnregisterNode(context.Context, *NodeRegisterRequest) (*emptypb.Empty, error)
	Heartbeat(context.Context, *NodeHeartbeat) (*emptypb.Empty, error)
}

// UnimplementedNodeManagementServer should be embedded to have forward compatible implementations.
type UnimplementedNodeManagementServer struct {
}

func (UnimplementedNodeManagementServer) RegisterNode(context.Context, *NodeRegisterRequest) (*NodeRegisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedNodeManagementServer) UnregisterNode(context.Context, *NodeRegisterRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterNode not implemented")
}
func (UnimplementedNodeManagementServer) Heartbeat(context.Context, *NodeHeartbeat) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}

// UnsafeNodeManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeManagementServer will
// result in compilation errors.
type UnsafeNodeManagementServer interface {
	mustEmbedUnimplementedNodeManagementServer()
}

func RegisterNodeManagementServer(s *grpc.Server, srv NodeManagementServer) {
	s.RegisterService(&_NodeManagement_serviceDesc, srv)
}

func _NodeManagement_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeManagementServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.NodeManagement/RegisterNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeManagementServer).RegisterNode(ctx, req.(*NodeRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeManagement_UnregisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeManagementServer).UnregisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.NodeManagement/UnregisterNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeManagementServer).UnregisterNode(ctx, req.(*NodeRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeManagement_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeHeartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeManagementServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.NodeManagement/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeManagementServer).Heartbeat(ctx, req.(*NodeHeartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "controller.NodeManagement",
	HandlerType: (*NodeManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _NodeManagement_RegisterNode_Handler,
		},
		{
			MethodName: "UnregisterNode",
			Handler:    _NodeManagement_UnregisterNode_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _NodeManagement_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller.proto",
}

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigServiceClient interface {
	// HSI / PPPoE config CRUD
	CreateHSIConfig(ctx context.Context, in *CreateHSIConfigRequest, opts ...grpc.CallOption) (*HSIConfigResponse, error)
	UpdateHSIConfig(ctx context.Context, in *UpdateHSIConfigRequest, opts ...grpc.CallOption) (*HSIConfigResponse, error)
	DeleteHSIConfig(ctx context.Context, in *DeleteHSIConfigRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetHSIConfig(ctx context.Context, in *GetHSIConfigRequest, opts ...grpc.CallOption) (*HSIConfigResponse, error)
	ListHSIConfigs(ctx context.Context, in *ListHSIConfigsRequest, opts ...grpc.CallOption) (*ListHSIConfigsResponse, error)
	// PPPoE desire-state — same semantics as REST /pppoe/dial|hangup
	DialPPPoE(ctx context.Context, in *PPPoEActionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HangupPPPoE(ctx context.Context, in *PPPoEActionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Subscriber count
	SetSubscriberCount(ctx context.Context, in *SetSubscriberCountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetSubscriberCount(ctx context.Context, in *GetSubscriberCountRequest, opts ...grpc.CallOption) (*GetSubscriberCountResponse, error)
	// Static DNS records
	AddOrUpdateDNSRecord(ctx context.Context, in *DNSRecordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteDNSRecord(ctx context.Context, in *DeleteDNSRecordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListDNSRecords(ctx context.Context, in *ListDNSRecordsRequest, opts ...grpc.CallOption) (*ListDNSRecordsResponse, error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) CreateHSIConfig(ctx context.Context, in *CreateHSIConfigRequest, opts ...grpc.CallOption) (*HSIConfigResponse, error) {
	out := new(HSIConfigResponse)
	err := c.cc.Invoke(ctx, "/controller.ConfigService/CreateHSIConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) UpdateHSIConfig(ctx context.Context, in *UpdateHSIConfigRequest, opts ...grpc.CallOption) (*HSIConfigResponse, error) {
	out := new(HSIConfigResponse)
	err := c.cc.Invoke(ctx, "/controller.ConfigService/UpdateHSIConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) DeleteHSIConfig(ctx context.Context, in *DeleteHSIConfigRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/controller.ConfigService/DeleteHSIConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetHSIConfig(ctx context.Context, in *GetHSIConfigRequest, opts ...grpc.CallOption) (*HSIConfigResponse, error) {
	out := new(HSIConfigResponse)
	err := c.cc.Invoke(ctx, "/controller.ConfigService/GetHSIConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) ListHSIConfigs(ctx context.Context, in *ListHSIConfigsRequest, opts ...grpc.CallOption) (*ListHSIConfigsResponse, error) {
	out := new(ListHSIConfigsResponse)
	err := c.cc.Invoke(ctx, "/controller.ConfigService/ListHSIConfigs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) DialPPPoE(ctx context.Context, in *PPPoEActionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/controller.ConfigService/DialPPPoE", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) HangupPPPoE(ctx context.Context, in *PPPoEActionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/controller.ConfigService/HangupPPPoE", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) SetSubscriberCount(ctx context.Context, in *SetSubscriberCountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/controller.ConfigService/SetSubscriberCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetSubscriberCount(ctx context.Context, in *GetSubscriberCountRequest, opts ...grpc.CallOption) (*GetSubscriberCountResponse, error) {
	out := new(GetSubscriberCountResponse)
	err := c.cc.Invoke(ctx, "/controller.ConfigService/GetSubscriberCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) AddOrUpdateDNSRecord(ctx context.Context, in *DNSRecordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/controller.ConfigService/AddOrUpdateDNSRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) DeleteDNSRecord(ctx context.Context, in *DeleteDNSRecordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/controller.ConfigService/DeleteDNSRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) ListDNSRecords(ctx context.Context, in *ListDNSRecordsRequest, opts ...grpc.CallOption) (*ListDNSRecordsResponse, error) {
	out := new(ListDNSRecordsResponse)
	err := c.cc.Invoke(ctx, "/controller.ConfigService/ListDNSRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
// All implementations should embed UnimplementedConfigServiceServer
// for forward compatibility
type ConfigServiceServer interface {
	// HSI / PPPoE config CRUD
	CreateHSIConfig(context.Context, *CreateHSIConfigRequest) (*HSIConfigResponse, error)
	UpdateHSIConfig(context.Context, *UpdateHSIConfigRequest) (*HSIConfigResponse, error)
	DeleteHSIConfig(context.Context, *DeleteHSIConfigRequest) (*emptypb.Empty, error)
	GetHSIConfig(context.Context, *GetHSIConfigRequest) (*HSIConfigResponse, error)
	ListHSIConfigs(context.Context, *ListHSIConfigsRequest) (*ListHSIConfigsResponse, error)
	// PPPoE desire-state — same semantics as REST /pppoe/dial|hangup
	DialPPPoE(context.Context, *PPPoEActionRequest) (*emptypb.Empty, error)
	HangupPPPoE(context.Context, *PPPoEActionRequest) (*emptypb.Empty, error)
	// Subscriber count
	SetSubscriberCount(context.Context, *SetSubscriberCountRequest) (*emptypb.Empty, error)
	GetSubscriberCount(context.Context, *GetSubscriberCountRequest) (*GetSubscriberCountResponse, error)
	// Static DNS records
	AddOrUpdateDNSRecord(context.Context, *DNSRecordRequest) (*emptypb.Empty, error)
	DeleteDNSRecord(context.Context, *DeleteDNSRecordRequest) (*emptypb.Empty, error)
	ListDNSRecords(context.Context, *ListDNSRecordsRequest) (*ListDNSRecordsResponse, error)
}

// UnimplementedConfigServiceServer should be embedded to have forward compatible implementations.
type UnimplementedConfigServiceServer struct {
}

func (UnimplementedConfigServiceServer) CreateHSIConfig(context.Context, *CreateHSIConfigRequest) (*HSIConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHSIConfig not implemented")
}
func (UnimplementedConfigServiceServer) UpdateHSIConfig(context.Context, *UpdateHSIConfigRequest) (*HSIConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHSIConfig not implemented")
}
func (UnimplementedConfigServiceServer) DeleteHSIConfig(context.Context, *DeleteHSIConfigRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHSIConfig not implemented")
}
func (UnimplementedConfigServiceServer) GetHSIConfig(context.Context, *GetHSIConfigRequest) (*HSIConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHSIConfig not implemented")
}
func (UnimplementedConfigServiceServer) ListHSIConfigs(context.Context, *ListHSIConfigsRequest) (*ListHSIConfigsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHSIConfigs not implemented")
}
func (UnimplementedConfigServiceServer) DialPPPoE(context.Context, *PPPoEActionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DialPPPoE not implemented")
}
func (UnimplementedConfigServiceServer) HangupPPPoE(context.Context, *PPPoEActionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HangupPPPoE not implemented")
}
func (UnimplementedConfigServiceServer) SetSubscriberCount(context.Context, *SetSubscriberCountRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSubscriberCount not implemented")
}
func (UnimplementedConfigServiceServer) GetSubscriberCount(context.Context, *GetSubscriberCountRequest) (*GetSubscriberCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscriberCount not implemented")
}
func (UnimplementedConfigServiceServer) AddOrUpdateDNSRecord(context.Context, *DNSRecordRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOrUpdateDNSRecord not implemented")
}
func (UnimplementedConfigServiceServer) DeleteDNSRecord(context.Context, *DeleteDNSRecordRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDNSRecord not implemented")
}
func (UnimplementedConfigServiceServer) ListDNSRecords(context.Context, *ListDNSRecordsRequest) (*ListDNSRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDNSRecords not implemented")
}

// UnsafeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s *grpc.Server, srv ConfigServiceServer) {
	s.RegisterService(&_ConfigService_serviceDesc, srv)
}

func _ConfigService_CreateHSIConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHSIConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).CreateHSIConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ConfigService/CreateHSIConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).CreateHSIConfig(ctx, req.(*CreateHSIConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_UpdateHSIConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHSIConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).UpdateHSIConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ConfigService/UpdateHSIConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).UpdateHSIConfig(ctx, req.(*UpdateHSIConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_DeleteHSIConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHSIConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).DeleteHSIConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ConfigService/DeleteHSIConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).DeleteHSIConfig(ctx, req.(*DeleteHSIConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetHSIConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHSIConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetHSIConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ConfigService/GetHSIConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetHSIConfig(ctx, req.(*GetHSIConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ListHSIConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHSIConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ListHSIConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ConfigService/ListHSIConfigs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ListHSIConfigs(ctx, req.(*ListHSIConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_DialPPPoE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PPPoEActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).DialPPPoE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ConfigService/DialPPPoE",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).DialPPPoE(ctx, req.(*PPPoEActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_HangupPPPoE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PPPoEActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).HangupPPPoE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ConfigService/HangupPPPoE",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).HangupPPPoE(ctx, req.(*PPPoEActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_SetSubscriberCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSubscriberCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).SetSubscriberCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ConfigService/SetSubscriberCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).SetSubscriberCount(ctx, req.(*SetSubscriberCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetSubscriberCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscriberCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetSubscriberCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ConfigService/GetSubscriberCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetSubscriberCount(ctx, req.(*GetSubscriberCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_AddOrUpdateDNSRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DNSRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).AddOrUpdateDNSRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ConfigService/AddOrUpdateDNSRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).AddOrUpdateDNSRecord(ctx, req.(*DNSRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_DeleteDNSRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDNSRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).DeleteDNSRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ConfigService/DeleteDNSRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).DeleteDNSRecord(ctx, req.(*DeleteDNSRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ListDNSRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDNSRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ListDNSRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.ConfigService/ListDNSRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ListDNSRecords(ctx, req.(*ListDNSRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConfigService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "controller.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHSIConfig",
			Handler:    _ConfigService_CreateHSIConfig_Handler,
		},
		{
			MethodName: "UpdateHSIConfig",
			Handler:    _ConfigService_UpdateHSIConfig_Handler,
		},
		{
			MethodName: "DeleteHSIConfig",
			Handler:    _ConfigService_DeleteHSIConfig_Handler,
		},
		{
			MethodName: "GetHSIConfig",
			Handler:    _ConfigService_GetHSIConfig_Handler,
		},
		{
			MethodName: "ListHSIConfigs",
			Handler:    _ConfigService_ListHSIConfigs_Handler,
		},
		{
			MethodName: "DialPPPoE",
			Handler:    _ConfigService_DialPPPoE_Handler,
		},
		{
			MethodName: "HangupPPPoE",
			Handler:    _ConfigService_HangupPPPoE_Handler,
		},
		{
			MethodName: "SetSubscriberCount",
			Handler:    _ConfigService_SetSubscriberCount_Handler,
		},
		{
			MethodName: "GetSubscriberCount",
			Handler:    _ConfigService_GetSubscriberCount_Handler,
		},
		{
			MethodName: "AddOrUpdateDNSRecord",
			Handler:    _ConfigService_AddOrUpdateDNSRecord_Handler,
		},
		{
			MethodName: "DeleteDNSRecord",
			Handler:    _ConfigService_DeleteDNSRecord_Handler,
		},
		{
			MethodName: "ListDNSRecords",
			Handler:    _ConfigService_ListDNSRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller.proto",
}
